### ISSUE TITLE
Error 404 while fetching spark

### ISSUE THREAD

**Issue by zyioump** [OpenPathView/OPV_Ansible#40]
Downloading Spark ...
--2018-07-20 14:54:34--  http://apache.crihan.fr/dist/spark/spark-2.2.1/spark-2.2.1-bin-hadoop2.7.tgz
Résolution de apache.crihan.fr (apache.crihan.fr)… 195.221.21.36, 2001:660:7401:211::36
Connexion à apache.crihan.fr (apache.crihan.fr)|195.221.21.36|:80… connecté.
requête HTTP transmise, en attente de la réponse… 404 Not Found
2018-07-20 14:54:34 erreur 404 : Not Found.

**Comment by Benvii** [comment]
I have the image locally, I uploaded it to : https://storage.openpathview.fr/ansible/files/spark-2.2.1-bin-hadoop2.7.tgz 

@zyioump can you update getSpark.sh to use this archive ?
https://github.com/OpenPathView/OPV_Ansible/blob/master/get_Spark.sh#L15
